# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_uploadfile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='photofile',
            field=models.FileField(default='', upload_to='files'),
            preserve_default=False,
        ),
    ]
