# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170222_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='filename',
            field=models.TextField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
