# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_uploadfile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='filename',
            field=models.CharField(max_length=40),
        ),
    ]
