# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170304_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='filename',
        ),
    ]
