# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_uploadfile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
    ]
