# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='file1',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='file2',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
